### ISSUE TITLE
FR: spread menu to fewer lines

### ISSUE THREAD

**Issue by improvethings** [vishalxl/nostr_console#23]
If I have a full screen terminal/console, spread the main menu at the bottom along 2-3 lines at most, so I get more feed based content on my screen. 10 lines taken up all the time is unnecessary

**Comment by vishalxl** [comment]
i've reduced 2-3 lines in a upcoming new version. so that's my priority too. will keep that in mind.

**Comment by vishalxl** [comment]
would you find it useful if menu is printed horizontally in 1-2 lines? That can be done, ideally as an option.

**Comment by vishalxl** [comment]
Printed menus horizontally. Fixed in [0.1.2 release](https://github.com/vishalxl/nostr_console/releases/tag/v0.1.2-beta).

**Comment by vishalxl** [comment]
<img width="1280" alt="2022-11-14" src="https://user-images.githubusercontent.com/64505169/201542434-1b7a81fe-a154-4bed-997f-5806d2c7b6d3.png">

New horizontal menu with version 0.1.3-beta

**Comment by improvethings** [comment]
You can remove "Main Menu" and put it on the next line: "Main menu options:" instead of Pick an option:. 
You can put the Signed in as: $user aligned right on the "Main menu options:" line, to knock off another line. This would gain 2 extra lines for content.

**Comment by vishalxl** [comment]
Combined and did reduce one line.. thanks for suggestions. 

![Uploading 2022-11-15 (3).png…]()

**Comment by vishalxl** [comment]
Combined and did reduce one line.. thanks for suggestions.



<img width="1280" alt="2022-11-15 (3)" src="https://user-images.githubusercontent.com/64505169/201820339-1b8acef6-0b91-456b-b6ea-18dce80427b5.png">
