### ISSUE TITLE
FR: Notifcations Main Menu option

### ISSUE THREAD

**Issue by improvethings** [vishalxl/nostr_console#29]
I propose a new Main Menu option:  3. Notifications
When I click 3, I get a chronological list of the last messages to me that I can then choose to reply to or not. This might even be better to put as #1 or #2 in the main menu, as when I log in, the first thing I want to see are notifications so I can reply to any threads looking for my input, only after I've replied to those, do I want to go to the Display feed.

**Comment by vishalxl** [comment]
So there will be three such menus

1. Show Feed ( which will show the home page)
2. Show Notifications ( which will show the notifications sent to the user, the replies and likes they got)
3. Show All New Posts ( global new posts and likes by everybody)

Then the 'write post/reply' menu will go to number 4.

**Comment by vishalxl** [comment]
New change: Added 'social network menu', which will have kind 1 network related options, including replying or creating kind 1 posts and reactions. 

First pic is the main menu: 
<img width="1280" alt="2022-11-24 (3)" src="https://user-images.githubusercontent.com/64505169/203649848-b1dd2462-4540-4eaf-b9b5-96f4c65154b3.png">

2nd pic is the new social network menu; it will also have other kind 1 related options like show profile etc. 
<img width="1280" alt="2022-11-24 (5)" src="https://user-images.githubusercontent.com/64505169/203649852-c361becc-c4b4-4483-acee-880909c94b32.png">

**Comment by vishalxl** [comment]
Now there is options for seeing your notifications in the new 'social network' menu. 

I am logged in using your pubkey and seeing this : 
<img width="1280" alt="2022-11-24 (8)" src="https://user-images.githubusercontent.com/64505169/203790057-3ddddc05-967e-4eda-8ee6-0450a83be34c.png">

**Comment by vishalxl** [comment]
Fixed with version [v0.1.8-beta](https://github.com/vishalxl/nostr_console/releases/tag/v0.1.8-beta) .

**Comment by improvethings** [comment]
This is great! For notifications, I feel the screen should always be filled with your last notifications, but colour coded or made clear which ones haven't been read it. For example, I might see a notification but not have time to respond, I'd like to be able to go back into notifications later and see it.

**Comment by vishalxl** [comment]
right now if a notification is printed, there is no way to know which a user has read and which they haven't. 

The only thing can be done is to keep the unresponded notifications as notifications, but even that would be more complicated than the effort, so for now i will just keep it like as it is: where user notifications means any response they have recieved ( whether they've responded to it or not).
