### ISSUE TITLE
Allow for special chars in input

### ISSUE THREAD

**Issue by johnnyasantoss** [vishalxl/nostr_console#39]
I just tried nostr console and after typing "re" (miss clicked) and then correcting to "é" my message got screwed up. It was showing up correctly on my side, but was sent differently

Minor ux issue for those using english international I guess.

![image](https://user-images.githubusercontent.com/14189387/208327324-80fcbf0d-513e-422d-bfca-7434b14003b5.png)

**Comment by vishalxl** [comment]
hey, this is a known issue in Windows Terminal. unless you are using some other platform, let me know. Will fix it over time. 

On ubuntu you can paste special characters, even smileys from other messengers etc, and they get sent.

**Comment by vishalxl** [comment]
Closing this because this is mentioned in the todo list in main readme, and is planned to be done.

**Comment by johnnyasantoss** [comment]
I was using with linux + alacritty
