### ISSUE TITLE
Conflicting IDs when truncated at 4?

### ISSUE THREAD

**Issue by armstrys** [vishalxl/nostr_console#40]
I haven't been able to totally debug this, but I think the IDs as displayed in nostr_console may be too short to avoid conflicts given the increased usage.

I attempted to send a delete request for id "20c2" and received the response
`Invalid Event Id(s). Kindly enter a more unique id.`

Since the console truncates the ID at 4 I went to another client and was able to send the delete request using more characters. I assume there was a conflicting ID, but didn't have to tools to find it. Maybe worth upping the default length of ID display in the terminal?

**Comment by vishalxl** [comment]
Yes, this needs to be done now with the influx. Will do that in next iteration. This is needed for replies etc. 

But delete replies I think need whole 64 bytes length, no? Not sure. You can find your event in event file in case you want from the prefix or content, btw.

**Comment by armstrys** [comment]
Thanks that’s good to know!

**Comment by vishalxl** [comment]
Since this is part of readme as todo, and planned to be done, closing this for now.
