### ISSUE TITLE
unable to make a post, no errors?

### ISSUE THREAD

**Issue by themariner7289** [vishalxl/nostr_console#42]
Trying to create a new post in the social menu.  My post never shows up in the list of my posts?  I'm passing in a relay, and private key.  All seems to work, just not posts.  Likes work, and replies work..

edit: likes might not work.. hm, actually not sure if any of the post stuff works..

edit2: running master branch

**Comment by themariner7289** [comment]
also tried the binary for 0.2.6-beta, same result.

**Comment by vishalxl** [comment]
the binary is from main branch only. 

its likely due to relay problem. note that 1 out of 10 times, a message/like etc may not actually go. this is a known issue. so could be that, or some relay problem.

**Comment by themariner7289** [comment]
I think you're right, testing some more and maybe i was just impatient and relays are bogged down.  Closing.
