### ISSUE TITLE
my client doesn't seem to load all the events from "all_nostr_events.txt"

### ISSUE THREAD

**Issue by jeremyd** [vishalxl/nostr_console#46]
When I run nostr_console.exe with --relay wss://nostr-pub.wellorder.net,wss://relay.damus.io,wss://relay.nostr.info,wss://nostr-relay.wlvs.space,wss://nostr.radixrat.com

it doesn't always load all the posts/replies (i only notice because I check in my 2. social, 5. replies/likes, and 6. friends).  It will have some of the messages    Non: Event not loaded .  I will also notice that certain people I'm following don't have their friendly name, it didn't load those either.

This seems to be a little different, if i specify --request="[\"REQ\",\"cn\",{\"limit\":200000,\"kinds\":[0,1,3,4,104,140,141,142],\"since\":1668984662}]"

Then the replies and etc are all filled in, and friends names are filled in.

After playing around a lot and quitting and restarting, I notice that nostr_console only loads 4955 posts, regardless how big my all_nostr_events.txt is (right now it's a whopping 1.1Gb of events).

Reading events from  default  file.......read 4955 posts from file all_nostr_events.txt

I also noticed, everytime I quit, it's appending 8000+ posts, so why would it only load 4955?  There has to be more than that in the file..

Appended 21338 new events to file "all_nostr_events.txt" of which 7998 are posts.

Lmk if I can provide any more info..

**Comment by jeremyd** [comment]
This was tested running main branch @ fdc7f7cb1d9da72c96cb13e568e1256b26afd660 (latest)

**Comment by jeremyd** [comment]
Trying with a fresh all_nostr_events.txt, started console

read 0 posts from file all_nostr_events.txt

quit the console 

Reading events from  default  file.......read 12753 posts from file all_nostr_events.txt

This matches! Perhaps there was something bad in the previous file that was preventing loading @ 4955 posts each time?  I also notice the problems also went away as far as not seeing the friends/posts..

**Comment by vishalxl** [comment]
Somebody has been sending 200kb events today. Possibly due to that the file size went so high. There was no size check in console code; which I am fixing now.
