### ISSUE TITLE
Support "npub1" public keys

### ISSUE THREAD

**Issue by seth586** [vishalxl/nostr_console#48]
Kinda frustrating having to convert to hex, can we just add support for 'npub1' public keys?

**Comment by vishalxl** [comment]
Yes, its the first item in todo list in readme. 

Right now I am just fixing some connection issues, then will do the npub feature. Will take a couple days still.

**Comment by vishalxl** [comment]
Latest build from Actions now has support for nsec key with --prikey option ( same with npub key too).
