### ISSUE TITLE
nostr console is filling up syslog file with 100s of GB of data

### ISSUE THREAD

**Issue by ibenoni** [vishalxl/nostr_console#49]
After using it for an hour or so, I started getting notifications that my drive is almost full. After checking syslog file ( Ubuntu ) , it was almost 200GB in size and all are nostr console logs and errors.

**Comment by vishalxl** [comment]
Seems to be same as [this issue](https://github.com/vishalxl/nostr_console/issues/15) seen in Kubuntu.

Can you check a few lines of what is being written to that log and where?

**Comment by vishalxl** [comment]
hi, can you try this [fix](https://github.com/vishalxl/nostr_console/actions/runs/3781479802)

Its a fix in that it will exit the program if the program is not getting any input from the terminal. Which is what seems to be happening.

**Comment by ibenoni** [comment]
> Seems to be same as [this issue](https://github.com/vishalxl/nostr_console/issues/15) seen in Kubuntu.
> 
> Can you check a few lines of what is being written to that log and where?

Yes. The same issue. 
File: /var/log/syslog

**Comment by vishalxl** [comment]
ok. 

did you try the version in link I shared? It has an attempt at a fix...

**Comment by vishalxl** [comment]
The proper release with an attempt at fix is [here](https://github.com/vishalxl/nostr_console/releases/tag/v0.3.1-beta) version 0.3.1

**Comment by gzuuus** [comment]
Had the same problem, solved with version 0.3.1

**Comment by vishalxl** [comment]
Nice to know its solved. Thanks for the feedback(s).
