### ISSUE TITLE
Wrapping a dart/flutter nostr library

### ISSUE THREAD

**Issue by ethicnology** [vishalxl/nostr_console#50]
Are you going to wrap functions into a dart/flutter library, so we can use it in Flutter ?

**Comment by vishalxl** [comment]
The most or only useful functions are the crypto related functions. Rest of almost all code is application specific, and its not that great design either!

The crypto functions are about 140 lines of code [here](https://github.com/vishalxl/nostr_console/blob/43b7e285ef1f99b5b2682c6cd2d02394d78aabed/lib/event_ds.dart#L1466) , generate pvt key, encrypt and decrypt. 

I am not sure if they should be in their own lib. Not very familiar with library creation too in Dart.

**Comment by ethicnology** [comment]
Thank you for the hint.

Today, I've started to implement a [nostr library](https://github.com/ethicnology/dart-nostr) in dart with the NIP01

If you want to collaborate or give feedbacks it would be really cool, or even if you want to talk (vocal?) about nostr to share your knowledge which is far deeper than mine.

**Comment by vishalxl** [comment]
I will write some notes etc for developers, in a bit.

**Comment by saentari** [comment]
Good initiative [ethicnology](https://github.com/ethicnology). I'll see if I can help.

**Comment by ethicnology** [comment]
https://github.com/ethicnology/dart-nostr

Don't hesitate to contribute if you develop new NIP
