### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by umop3plsdn** [vishalxl/nostr_console#77]
it's actually printing out 18 global threads but immediately dies right after saying either 
Unhandled exception:
HandshakeException: Connection terminated during handshake
or 
Unhandled exception:
HttpException: Connection closed before full header was received, uri = https://relay.damus.io:0

**Comment by umop3plsdn** [comment]
I also get:
Could not find your contact list.
Waiting for feed to come in..............Unhandled exception:
WebSocketException: Connection to 'https://nostr.bitcoiner.social:0#' was not upgraded to websocket
#0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
#1      WebSocket.connect (dart:_http/websocket.dart:320:22)
#2      new IOWebSocketChannel.connect (package:web_socket_channel/io.dart:80:28)
#3      Relays.sendRequest (package:nostr_console/relays.dart:166:56)
#4      Relays.getMultiUserEvents (package:nostr_console/relays.dart:142:5)
#5      getMultiUserEvents (package:nostr_console/relays.dart:295:14)
#6      main.<anonymous closure> (file:///home/da5id/repos/nostr_console/bin/nostr_console.dart:389:9)
#7      new Future.delayed.<anonymous closure> (dart:async/future.dart:424:39)
#8      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by glasgowm148** [comment]
Same issue on OSX

**Comment by gzuuus** [comment]
Same in ubuntu since the last release

**Comment by twofaktor** [comment]
Same issue on Raspbian OS lite arm64:
```sh
Waiting for feed to come in..............Unhandled exception:
WebSocketException: Connection to 'https://nostr-relay.trustbtc.org:0#' was not upgraded to websocket
#0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011)
#1      WebSocket.connect (dart:_http/websocket.dart:320)
#2      new IOWebSocketChannel.connect (package:web_socket_channel/io.dart:80)
#3      Relays.sendRequest (package:nostr_console/relays.dart:166)
#4      Relays.getMultiUserEvents (package:nostr_console/relays.dart:142)
#5      getMultiUserEvents (package:nostr_console/relays.dart:295)
#6      main.<anonymous closure> (file:///work/bin/nostr_console.dart:389)
#7      new Future.delayed.<anonymous closure> (dart:async/future.dart:424)
#8      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

**Comment by vishalxl** [comment]
I have made some progress in fixing this: have actually googled the error and landed [here](https://github.com/dart-lang/web_socket_channel/issues/38) hah. Hope to fix it soon.

**Comment by prg4hire** [comment]
With the [commit 87b018f](https://github.com/vishalxl/nostr_console/commit/87b018face8c4dc7ebec520efdccbf000a0c7b0a) , the exception is caught, I've done minimal testing and see the exception getting caught.

**Comment by vishalxl** [comment]
This is not seen in latest build.
