### ISSUE TITLE
Error on -k options key

### ISSUE THREAD

**Issue by yshwanth** [vishalxl/nostr_console#82]
Error: The getter 'ready' isn't defined for the class 'IOWebSocketChannel'.
 - 'IOWebSocketChannel' is from 'package:web_socket_channel/io.dart' ('../.pub-cache/hosted/pub.dev/web_socket_channel-2.2.0/lib/io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ready'.

**Comment by vishalxl** [comment]
This issue is not seen in Windows as of now.
