### ISSUE TITLE
Release is broken.

### ISSUE THREAD

**Issue by ghost** [vishalxl/nostr_console#84]
Default relays are used despite specifying relay. Default relay cannot connect and crashes the program.

./nostr_console_linux_amd64 -r wss://nos.lol
app start time: 2024-09-27 15:54:23.144423

           ▀█▄   ▀█▀                  ▄           
            █▀█   █    ▄▄▄    ▄▄▄▄  ▄██▄  ▄▄▄ ▄▄  
            █ ▀█▄ █  ▄█  ▀█▄ ██▄ ▀   ██    ██▀ ▀▀ 
            █   ███  ██   ██ ▄ ▀█▄▄  ██    ██     
           ▄█▄   ▀█▄  ▀█▄▄█▀ █▀▄▄█▀  ▀█▄▀ ▄██▄    
 
  ██████╗ ██████╗ ███╗   ██╗███████╗ ██████╗ ██╗     ███████╗
 ██╔════╝██╔═══██╗████╗  ██║██╔════╝██╔═══██╗██║     ██╔════╝
 ██║     ██║   ██║██╔██╗ ██║███████╗██║   ██║██║     █████╗  
 ██║     ██║   ██║██║╚██╗██║╚════██║██║   ██║██║     ██╔══╝  
 ╚██████╗╚██████╔╝██║ ╚████║███████║╚██████╔╝███████╗███████╗
  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚══════╝╚══════╝

You should ideally create your own private key and use it with --prikey program argument. 
Create a private key from astral.ninja, @damusapp, or even from command line using `openssl rand -hex 32`..

npub/nsec keys can be converted to hex key format using https://damus.io/key
Primary relays that will be used: wss://nos.lol
Reading events from  default  file.......read 0 events from file all_nostr_events.txt

For new users: The app only gets kind 1 events from people you follow or some popular well known pubkeys. 
  If you see a message such as 'event not loaded' it implies its from someone you don't follow. Such events 
  are eventually loaded; however, the ideal way to use this app is to follow people whose posts you want to read or follow.

Waiting for user posts to come in........done
Waiting for feed to come in..............Unhandled exception:
SocketException: Failed host lookup: 'nostr.zerofeerouting.com' (OS Error: Name or service not known, errno = -2)
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1827)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:299)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:77)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2449)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2867)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2872)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2727)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2591)
#10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1021)
#11     WebSocket.connect (dart:_http/websocket.dart:320)
#12     new IOWebSocketChannel.connect (package:web_socket_channel/io.dart:80)
#13     Relays.sendRequest (package:nostr_console/relays.dart:166)
#14     Relays.getMultiUserEvents (package:nostr_console/relays.dart:142)
#15     getMultiUserEvents (package:nostr_console/relays.dart:295)
#16     main.<anonymous closure> (file:///work/bin/nostr_console.dart:389)
#17     new Future.delayed.<anonymous closure> (dart:async/future.dart:424)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

according to ./nostr_console_linux_amd64 --help, -r argument is supposed to replace predefined relays, but it does not behave like that.

-r, --relay   <relay urls>    The comma separated relay urls that are used as main relays. If given, these are used rather than the default relays.

**Comment by 111111111111111111111111111111111111110** [comment]
building from master branch works, so i guess release is outdated

**Comment by vishalxl** [comment]
There were fixes in master branch, after last release, which avoids this crash that you are seeing. Thanks for confirming.

**Comment by vishalxl** [comment]
The latest release as of now is from May 2024, here: https://github.com/vishalxl/nostr_console/releases/tag/v0.3.6-beta

You likely tested it using a previous release because the 3.6-beta was marked as pre-release, which I just fixed.
